name: BOT
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:

    - name: 1. Download File Bot
      run: |
        Invoke-WebRequest https://github.com/AyGemuy/CloudBot/archive/refs/heads/main.zip -OutFile main.zip

    - name: 2. Mengkstrak File BOT
      run: Expand-Archive main.zip

    - name: 4. Mengaktifkan BOT
      run: npm install
      
      - name: 5. Mengaktifkan BOT
      run: npm start
      
      
